/**
 * Mapping símbolo → nombre canónico para los pares más populares.
 * Binance solo nos da el ticker, así que usamos esto para mostrar nombres
 * lindos en el frontend (BTC → "Bitcoin", ICP → "Internet Computer", etc.).
 *
 * Si una cripto no está en este mapping, se muestra el ticker como nombre.
 */
export const COIN_NAMES: Record<string, string> = {
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  USDT: 'Tether',
  USDC: 'USD Coin',
  BNB: 'BNB',
  SOL: 'Solana',
  XRP: 'XRP',
  ADA: 'Cardano',
  DOGE: 'Dogecoin',
  TRX: 'TRON',
  TON: 'Toncoin',
  AVAX: 'Avalanche',
  DOT: 'Polkadot',
  MATIC: 'Polygon',
  LINK: 'Chainlink',
  LTC: 'Litecoin',
  BCH: 'Bitcoin Cash',
  XLM: 'Stellar',
  ATOM: 'Cosmos',
  ICP: 'Internet Computer',
  NEAR: 'NEAR Protocol',
  APT: 'Aptos',
  ARB: 'Arbitrum',
  OP: 'Optimism',
  FIL: 'Filecoin',
  HBAR: 'Hedera',
  VET: 'VeChain',
  ALGO: 'Algorand',
  AAVE: 'Aave',
  MKR: 'Maker',
  UNI: 'Uniswap',
  GRT: 'The Graph',
  IMX: 'Immutable',
  RNDR: 'Render',
  INJ: 'Injective',
  TIA: 'Celestia',
  SUI: 'Sui',
  SEI: 'Sei',
  PEPE: 'Pepe',
  SHIB: 'Shiba Inu',
  WIF: 'dogwifhat',
  BONK: 'Bonk',
  FLOKI: 'Floki',
  CRO: 'Cronos',
  STX: 'Stacks',
  RUNE: 'THORChain',
  ETC: 'Ethereum Classic',
  XMR: 'Monero',
  XTZ: 'Tezos',
  EOS: 'EOS',
  IOTA: 'IOTA',
  ZIL: 'Zilliqa',
  ENJ: 'Enjin Coin',
  SAND: 'The Sandbox',
  MANA: 'Decentraland',
  AXS: 'Axie Infinity',
  GALA: 'Gala',
  CHZ: 'Chiliz',
  FTM: 'Fantom',
  HNT: 'Helium',
  KAS: 'Kaspa',
  ORDI: 'ORDI',
  PYTH: 'Pyth Network',
  JUP: 'Jupiter',
  ENA: 'Ethena',
  WLD: 'Worldcoin',
  STRK: 'Starknet',
  DYDX: 'dYdX',
  AR: 'Arweave',
  EGLD: 'MultiversX',
  THETA: 'Theta Network',
  FLOW: 'Flow',
};
